name: byourside
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  firebase_core: ^2.14.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.0.3
  google_sign_in: ^6.1.4
  url_launcher: ^6.1.14
  firebase_storage:
  logger: ^1.1.0
  permission_handler:
  firebase_app_check: ^0.1.5-1 
  get: ^4.6.5
  carousel_slider:
  carousel_indicator:
  flutter_dotenv: ^5.0.2
  firebase_storage_mocks: ^0.6.1
  fake_cloud_firestore: ^2.4.1+1
  firebase_crashlytics: ^3.3.3
  mockito: ^5.4.2
  sign_in_with_apple: ^5.0.0
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^14.1.1
  flutter_svg: ^2.0.7
  dots_indicator: ^2.1.2
  easy_rich_text: ^2.0.0
  crypto: ^3.0.3
  introduction_screen: ^3.1.12
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.24.1
flutter_icons:
  android: "android_app_logo"
  ios: true
  # 추후에 로고 바뀌면 image_path와 path_ios는 appstore, foreground는 playsotre로 설정
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/config/.env
    - assets/icons/option.svg
    - assets/icons/add_post.svg
    - assets/icons/auto_information.svg
    - assets/icons/auto_information_bgr.svg
    - assets/icons/back.svg
    - assets/icons/comment.svg
    - assets/icons/community_bgr.svg
    - assets/icons/community.svg
    - assets/icons/home_bgr.svg
    - assets/icons/home.svg
    - assets/icons/likes.svg
    - assets/icons/mypage_bgr.svg
    - assets/icons/mypage.svg
    - assets/icons/post_likes_full.svg
    - assets/icons/post_likes.svg
    - assets/icons/post_scrap_full.svg
    - assets/icons/post_scrap.svg
    - assets/icons/profile.svg
    - assets/icons/scrap_page.svg
    - assets/icons/scrap.svg
    - assets/icons/search.svg
    - assets/icons/authentication/login/apple_icon.svg
    - assets/icons/authentication/login/google_icon.svg
    - assets/icons/authentication/login/google_icon.png
    - assets/icons/authentication/login/beeside_logo.svg
    - assets/icons/authentication/login/bee_icon.svg
    - assets/icons/authentication/login/tos_line.svg
    - assets/icons/authentication/login/policy_line.svg
    - assets/icons/authentication/setup/participator.svg
    - assets/icons/authentication/setup/protector.svg
    - assets/icons/authentication/setup/self.svg
    - assets/icons/hobee.svg
    - assets/icons/logo.svg
    - assets/icons/see_more.svg
    - assets/icons/speech_bubble.svg
    - assets/icons/loading.gif
    - assets/icons/photo.svg
    - assets/icons/site.svg
    - assets/icons/onboarding_hobee.png
    - assets/icons/onboarding_autoInformation.svg
    - assets/icons/onboarding_community.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: KoddiUDOnGothic
      fonts:
        - asset: assets/fonts/KoddiUDOnGothic-Regular.otf
        - asset: assets/fonts/KoddiUDOnGothic-Bold.otf
        - asset: assets/fonts/KoddiUDOnGothic-ExtraBold.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages