name: byourside
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
  

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  firebase_core: ^2.14.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.0.3
  google_sign_in: ^6.1.4
  url_launcher: ^6.1.14
  firebase_storage:
  logger: ^1.1.0
  permission_handler:
  package_info_plus_web: ^2.0.0
  firebase_app_check: ^0.1.5-1 
  flutter_recaptcha_v3: ^0.1.3
  safetynet_attestation: ^0.0.5
  get: ^4.6.5
  carousel_slider:
  carousel_indicator:
  multiple_stream_builder: ^3.0.2
  percent_indicator: ^4.0.1
  flutter_dotenv: ^5.0.2
  google_sign_in_mocks: ^0.3.0
  firebase_auth_mocks: ^0.12.0
  firebase_storage_mocks: ^0.6.1
  fake_cloud_firestore: ^2.4.1+1
  font_awesome_flutter: ^10.5.0
  firebase_crashlytics: ^3.3.3
  mockito: ^5.4.2
  sign_in_with_apple: ^5.0.0
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^14.1.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.24.1

flutter_icons:
  android: "android_app_logo"
  ios: true
  # 추후에 로고 바뀌면 image_path와 path_ios는 appstore, foreground는 playsotre로 설정
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/config/.env
    - assets/icons/add-ons.svg
    - assets/icons/add_post.svg
    - assets/icons/auto_information.svg
    - assets/icons/auto_information_bgr.svg
    - assets/icons/back.svg
    - assets/icons/comment.svg
    - assets/icons/community_bgr.svg
    - assets/icons/community.svg
    - assets/icons/home_bgr.svg
    - assets/icons/home.svg
    - assets/icons/likes.svg
    - assets/icons/mypage_bgr.svg
    - assets/icons/mypage.svg
    - assets/icons/post_likes_full.svg
    - assets/icons/post_likes.svg
    - assets/icons/post_scrap_full.svg
    - assets/icons/post_scrap.svg
    - assets/icons/profile.svg
    - assets/icons/scrap_page.svg
    - assets/icons/scrap.svg
    - assets/icons/search.svg
    - assets/icons/authentication/login/apple_icon.svg
    - assets/icons/authentication/login/google_icon.svg
    - assets/icons/authentication/login/google_icon.png
    - assets/icons/authentication/login/beeside_logo.svg
    - assets/icons/authentication/login/bee_icon.svg
    - assets/icons/authentication/login/tos_line.svg
    - assets/icons/authentication/login/policy_line.svg
    - assets/icons/authentication/setup/participator.svg
    - assets/icons/authentication/setup/protector.svg
    - assets/icons/authentication/setup/self.svg
    - assets/icons/hobee.svg
    - assets/icons/logo.svg
    - assets/icons/see_more.svg
    - assets/icons/speech_bubble.svg
    - assets/icons/loading.gif
    - assets/icons/photo.svg
    - assets/icons/site.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: KoddiUDOnGothic
      fonts:
        - asset: assets/fonts/KoddiUDOnGothic-Regular.otf
        - asset: assets/fonts/KoddiUDOnGothic-Bold.otf
        - asset: assets/fonts/KoddiUDOnGothic-ExtraBold.otf
    - family: IBMPlexSansKR
      fonts:
        - asset: assets/fonts/IBMPlexSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansKR-Bold.ttf
          weight: 700
    - family: NanumMyeongjo
      fonts:
        - asset: assets/fonts/NanumMyeongjo-Regular.ttf
          weight: 500
        - asset: assets/fonts/NanumMyeongjo-Bold.ttf
          weight: 700
        - asset: assets/fonts/NanumMyeongjo-ExtraBold.ttf
          weight: 900
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf
          weight: 500
        - asset: assets/fonts/NanumGothic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NanumGothic-ExtraBold.ttf
          weight: 900
