// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: '6LdtvqkjAAAAALWlvmPxUEoi3Sj2bsjbJmJt1Uw8',
//     appId: '1:334257891538:android:eb935bdef1b2dadef4250b',
//     messagingSenderId: '334257891538',
//     projectId: 'byourside-2ea11',
//     databaseURL: 'https://byourside-2ea11-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'byourside-2ea11.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDsKf4gZBp2jr45uVGOn3Wy8e1GCz13QDU',
//     appId: '1:334257891538:ios:1048563fff6954daf4250b',
//     messagingSenderId: '334257891538',
//     projectId: 'byourside-2ea11',
//     databaseURL: 'https://byourside-2ea11-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'byourside-2ea11.appspot.com',
//     androidClientId: '334257891538-87fos7j04h6kbl8boevhsngidiv36a6j.apps.googleusercontent.com',
//     iosClientId: '334257891538-llj35u2n9u73iq1ffcka8oop81sktc2o.apps.googleusercontent.com',
//     iosBundleId: 'com.example.byourside',
//   );
// }
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNy2VUKHiqvPKA9YmbyoqxTmjuJ6Oht1A',
    appId: '1:334257891538:web:3f21b8a0ff1db890f4250b',
    messagingSenderId: '334257891538',
    projectId: 'byourside-2ea11',
    authDomain: 'byourside-2ea11.firebaseapp.com',
    databaseURL: 'https://byourside-2ea11-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'byourside-2ea11.appspot.com',
    measurementId: 'G-814L9LZQT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWFz5BCw8LBVqVuyuEaGne5cxbwIxFiMM',
    appId: '1:334257891538:android:eb935bdef1b2dadef4250b',
    messagingSenderId: '334257891538',
    projectId: 'byourside-2ea11',
    databaseURL: 'https://byourside-2ea11-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'byourside-2ea11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsKf4gZBp2jr45uVGOn3Wy8e1GCz13QDU',
    appId: '1:334257891538:ios:1048563fff6954daf4250b',
    messagingSenderId: '334257891538',
    projectId: 'byourside-2ea11',
    databaseURL: 'https://byourside-2ea11-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'byourside-2ea11.appspot.com',
    androidClientId: '334257891538-87fos7j04h6kbl8boevhsngidiv36a6j.apps.googleusercontent.com',
    iosClientId: '334257891538-llj35u2n9u73iq1ffcka8oop81sktc2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.byourside',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsKf4gZBp2jr45uVGOn3Wy8e1GCz13QDU',
    appId: '1:334257891538:ios:1048563fff6954daf4250b',
    messagingSenderId: '334257891538',
    projectId: 'byourside-2ea11',
    databaseURL: 'https://byourside-2ea11-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'byourside-2ea11.appspot.com',
    androidClientId: '334257891538-87fos7j04h6kbl8boevhsngidiv36a6j.apps.googleusercontent.com',
    iosClientId: '334257891538-llj35u2n9u73iq1ffcka8oop81sktc2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.byourside',
  );
}