name: Flutter CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
    
jobs:
  build:
    name: Running Test and CI / CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.10.1'
      
      - name: Import Flutter Package
        run: |
          flutter pub get
    
      - name: Set up environment variables
        run: |
          mkdir -p assets/config/
          echo "WEB_RECAPTCHA_SITE_KEY=${{ secrets.WEB_RECAPTCHA_SITE_KEY }}" >> assets/config/.env
          echo "WEB_MESSAGING_SENDER_ID=${{ secrets.WEB_MESSAGING_SENDER_ID }}" >> assets/config/.env
          echo "WEB_MEASUREMENT_ID=${{ secrets.WEB_MEASUREMENT_ID }}" >> assets/config/.env
          echo "WEB_APP_ID=${{ secrets.WEB_APP_ID }}" >> assets/config/.env
          echo "WEB_API_KEY=${{ secrets.WEB_API_KEY }}" >> assets/config/.env

          echo "MACOS_MESSAGING_SENDER_ID=${{ secrets.MACOS_MESSAGING_SENDER_ID }}" >> assets/config/.env
          echo "MACOS_IOS_CLIENT_ID=${{ secrets.MACOS_IOS_CLIENT_ID }}" >> assets/config/.env
          echo "MACOS_APP_ID=${{ secrets.MACOS_APP_ID }}" >> assets/config/.env
          echo "MACOS_API_KEY=${{ secrets.MACOS_API_KEY }}" >> assets/config/.env
          echo "MACOS_ANDROID_CLIENT_ID=${{ secrets.MACOS_ANDROID_CLIENT_ID }}" >> assets/config/.env
          echo "IOS_MESSAGING_SENDER_ID=${{ secrets.IOS_MESSAGING_SENDER_ID }}" >> assets/config/.env
          echo "IOS_IOS_CLIENT_ID=${{ secrets.IOS_IOS_CLIENT_ID }}" >> assets/config/.env
          echo "IOS_APP_ID=${{ secrets.IOS_APP_ID }}" >> assets/config/.env
          echo "IOS_API_KEY=${{ secrets.IOS_API_KEY }}" >> assets/config/.env
          echo "IOS_ANDROID_CLIENT_ID=${{ secrets.IOS_ANDROID_CLIENT_ID }}" >> assets/config/.env

          echo "ANDROID_MESSAGING_SENDER_ID=${{ secrets.ANDROID_MESSAGING_SENDER_ID }}" >> assets/config/.env
          echo "ANDROID_APP_ID=${{ secrets.ANDROID_APP_ID }}" >> assets/config/.env
          echo "ANDROID_API_KEY=${{ secrets.ANDROID_API_KEY }}" >> assets/config/.env

      - name: Test Flutter
        run: |
          flutter test

